"""Stable runtime constants for ch_diag schema version 5."""

from __future__ import annotations

ARTIFACT_SCHEMA_VERSION = 5
CONTENT_SCHEMA_VERSION = 5

ONE_SHOT_MODE = "one-shot"
SNAPSHOTS_MODE = "snapshots"
RUN_MODES = {ONE_SHOT_MODE, SNAPSHOTS_MODE}

LOCAL_COLLECTION_MODE = "local"
REMOTE_DB_ONLY_COLLECTION_MODE = "remote-db-only"
REMOTE_COLLECTION_MODE = "remote"
COLLECTION_MODES = {
    LOCAL_COLLECTION_MODE,
    REMOTE_DB_ONLY_COLLECTION_MODE,
    REMOTE_COLLECTION_MODE,
}

NODE_SCOPE = "node"
CLUSTER_SCOPE = "cluster"
TARGET_SCOPES = {NODE_SCOPE, CLUSTER_SCOPE}

DEFAULT_SQL_TIMEOUT_SECONDS = 5.0
DEFAULT_DATABASE_WORKERS = 4
DEFAULT_DATABASE_CLOSE_TIMEOUT_SECONDS = 5.0
DEFAULT_SHELL_TIMEOUT_SECONDS = 2.0
DEFAULT_MAX_RESULT_ROWS = 10_000
DEFAULT_MAX_RESULT_BYTES = 64 * 1024 * 1024
DEFAULT_MAX_ARTIFACT_BYTES = 128 * 1024 * 1024
DEFAULT_SNAPSHOT_DURATION_SECONDS = 10.0
DEFAULT_SNAPSHOT_INTERVAL_SECONDS = 5.0
MIN_SNAPSHOT_INTERVAL_SECONDS = 0.2
MAX_SNAPSHOT_COUNT = 360
DEFAULT_MAX_CLUSTER_TARGETS = 32
DEFAULT_MAX_SERIES_PER_CHART = 200
DEFAULT_MAX_POINTS_PER_SERIES = 2_000
DEFAULT_MAX_TOTAL_CHART_POINTS = 200_000

EXECUTABLE_CONTENT_SUFFIXES = {".py", ".sh", ".sql", ".yaml", ".yml"}
INTEGRITY_FILE = "integrity.sha256"
